name: college_app_server
description: Backend API на Dart Frog для мобильного приложения колледжа
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  dart_frog: ^1.2.0
  postgres: ^3.4.5           # PostgreSQL клиент (3.4.5+ чинит баг SCRAM-SHA-256)
  dart_jsonwebtoken: ^2.14.0 # JWT токены
  # argon2_pure: ^1.0.3        # Аргон2 для хеширования паролей
  # argon_pure: ^1.0.3
  uuid: ^4.4.0               # Генерация UUID
  dotenv: ^4.2.0             # Чтение .env файлов
  meta: ^1.15.0
  crypto: ^3.0.3
  mime: ^1.0.5               # Определение MIME-типов

dev_dependencies:
  test: ^1.25.0
  mocktail: ^1.0.4
  lints: ^4.0.0
